# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  timeout: 5000

development:
  adapter: postgresql
  timeout: 5000
  host: 127.0.0.1
  port: 5432
  database: sample_postgres_development
  pool: 5
  username: root
  password: password
